### ISSUE TITLE
what does the  std::atomic_flag _pool_mutex  do ? 

### ISSUE THREAD

**Issue by Rainboylvx** [domGitDev/sqlconncpp#1]
why use std::atomic_flag _pool_mutex? I think it has no effect.

**Comment by domGitDev** [comment]
Well that’s true if you aren’t using a multithreaded application. Otherwise you will have data race when erasing or appending index to set Indexes variable. Without maintaining set of indices you might release same connection index twice to the queue and two threads might be using same connection at same time.
